### ISSUE TITLE
Please set site title

### ISSUE THREAD

**Issue by 1000ch** [girliemac/girliemac.github.io#2]
- https://github.com/girliemac/girliemac.github.io/blob/master/feed.xml#l6

``` xml
<title type="text">{{ site.title }}</title>
```

The title element of `feed.xml` is blank now.
So `(No title)` is displayed on my rss reader. :crying_cat_face: 
I think `{{ site.name }}` works well.

**Comment by girliemac** [comment]
Aww, thank you for closing after 6 years!

**Comment by 1000ch** [comment]
Just noticed that it was being opened 😅
